#!/usr/bin/env python3
import argparse
from pathlib import Path
import yaml

SYMBOL = {"yes": r"\\checkmark", "no": r"\\texttimes", "partial": r"$\\sim$"}

HEADER = r"""% Auto-generated by generate_tables.py
% Requires: \\usepackage{amssymb} or \\usepackage{pifont} for \\checkmark (or define it), and \\usepackage{textcomp} for \\texttimes.
% If your template lacks these, you can replace symbols with Y/N.
"""

def tex_escape(s: str) -> str:
    return (s.replace('\\', r'\\textbackslash{}')
              .replace('&', r'\\&')
              .replace('%', r'\\%')
              .replace('$', r'\\$')
              .replace('#', r'\\#')
              .replace('_', r'\\_')
              .replace('{', r'\\{')
              .replace('}', r'\\}')
              .replace('^', r'\\^{}')
              .replace('~', r'\\~{}'))

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--spec', type=Path, required=True)
    ap.add_argument('--outdir', type=Path, required=True)
    args = ap.parse_args()

    spec = yaml.safe_load(args.spec.read_text())
    systems = spec['systems']
    args.outdir.mkdir(parents=True, exist_ok=True)

    rows = []
    for s in systems:
        rows.append(
            "{} & {} & {} & {} & {} & {} \\\\".format(
                tex_escape(s['name']),
                SYMBOL[s['aov_oblivious_verification']],
                SYMBOL[s['certified_release']],
                SYMBOL[s['constant_shape_transcript']],
                SYMBOL[s['governed_opening_trace']],
                SYMBOL[s['epoch_freshness']],
            )
        )

    table = HEADER + r"""
\\begin{table}[t]
\\centering
\\small
\\setlength{\\tabcolsep}{5pt}
\\begin{tabular}{lccccc}
\\toprule
\\textbf{System} & \\textbf{AOV@V} & \\textbf{Cert. release} & \\textbf{Const. shape} & \\textbf{Opening/trace} & \\textbf{Epoch fresh}\\\\
\\midrule
""" + "\n".join(rows) + r"""
\\bottomrule
\\end{tabular}
\\caption{Comparison against existing systems along PRIME-Ring's evaluation axes. Symbols: $\\checkmark$ (supported), $\\texttimes$ (not supported), $\\sim$ (partial support).}
\\label{tab:compare-systems}
\\end{table}
"""

    args.outdir.joinpath('table_compare_systems.tex').write_text(table)

    # Emit a short notes file too.
    notes_lines = ["- {}: {}".format(s['name'], s['notes']) for s in systems]
    args.outdir.joinpath('system_notes.md').write_text("\n".join(notes_lines) + "\n")

if __name__ == '__main__':
    main()
